export default {
  category: [
    {
      id: '1',
      category: 'Mouse',
      wicon: require('./pics/w1.png'),
      bicon: require('./pics/b1.png'),
    },
    {
      id: '2',
      category: 'keyboard',
      wicon: require('./pics/w2.png'),
      bicon: require('./pics/b2.png'),
    },
    {
      id: '3',
      category: 'LCD',
      wicon: require('./pics/w3.png'),
      bicon: require('./pics/b3.png'),
    },
    {
      id: '4',
      category: 'headphone',
      wicon: require('./pics/w4.png'),
      bicon: require('./pics/b4.png'),
    },
    {
      id: '5',
      category: 'mouse pad',
      wicon: require('./pics/w5.png'),
      bicon: require('./pics/b5.png'),
    },
  ],
  product: [
    {
      id: '1',
      categoryid: '1',
      name: 'Logitech G203 Lightsync',
      price: '21.88',
      type: 'USB',
      rating: '4.1',
      images: require('./pics/1.png'),
      description:
        'G203 Lightsync is ready to play with an 8,000 DPI sensor and customizable, vibrant Lightsync RGB. Lightsync RGB can be customized with color wave effects or patterns across - 16.8 million colors to suit your play style, setup, and mood. ',
    },
    {
      id: '2',
      categoryid: '1',
      name: 'Acer Predator Cestus 330',
      price: '53.74',
      type: 'USB',
      rating: '4.3',
      images: require('./pics/2.png'),
      description:
        'The Cestus 330 brings light to the battle as you fight with accuracy in comfort. With up to 16,000 DPI and 400 IPS tracking, accuracy comes with the territory. Deep customization options include 7 programmable buttons, 5 on-the-fly DPI settings and 16.8 Million RGB backlighting that you can control directly from Predator Quarter Master',
    },
    {
      id: '3',
      categoryid: '1',
      name: 'HyperX Pulsefire Dart ',
      price: '99.99',
      type: 'Wireless',
      rating: '4.5',
      images: require('./pics/3.png'),
      description:
        'HyperX Pulsefire Dart is a gaming-grade wireless mouse with a reliable 2. 4GHz RF connection that will make you wonder why you waited so long to cut the cord. A wireless adapter is included to extend the range for desktop PC setups. It is Qi Certified for wireless charging* and can last up to 50 hours** on a single charge',
    },
    {
      id: '4',
      categoryid: '1',
      name: 'Redragon M602',
      price: '75.15',
      type: 'USB',
      rating: '4.3',
      images: require('./pics/4.png'),
      description:
        'The Redragon GRIFFIN M602 RGB is superbly designed highly customizable wired gaming mouse. The mouse is designed for eSports Gaming Pros who demand the very best performance. The Gaming Mouse is elegantly and comfortable thanks to a contoured smooth ergonomic design and offers smooth and precise movements due its high precision sensor',
    },
    {
      id: '5',
      categoryid: '1',
      name: 'MageGee G10',
      price: '17.99',
      type: 'USB',
      rating: '3.8',
      images: require('./pics/5.png'),
      description:
        'MageGee G10 Gaming Mouse Wired, 7 Colors Breathing LED Backlit Gaming Mouse, 6 Adjustable DPI (up to 3200 DPI), Ergonomic Optical Computer Mouse with 7 Buttons for Windows PC Gamers',
    },
    {
      id: '6',
      categoryid: '2',
      name: 'Perixx PERIBOARD-317',
      price: '29.99',
      type: 'USB',
      rating: '4.2',
      images: require('./pics/6.png'),
      description:
        'Periboard-317 is a wired illuminated full size keyboard. One-piece design, cost effective, sturdy and durable for different usagesWhite LED backlight: bright and evenly distributed backlit keys, easy typing in lower light environment. Ideal for studio work, office. The backlit can be turned on and off.',
    },
    {
      id: '7',
      categoryid: '2',
      name: 'Perixx PERIBOARD-210 ',
      price: '27.5',
      type: 'USB',
      rating: '3.8',
      images: require('./pics/7.png'),
      description:
        'Perixx PERIBOARD-210 Full-Size Wired Keyboard A slim design keyboard with integrated number pad design. The scissor-key mechanism makes sure for every keypress to be stable and responsive. Enjoy a quiet and comfortable typing experience doing your daily tasks.',
    },
    {
      id: '8',
      categoryid: '2',
      name: 'Mafiti ',
      price: '14.75',
      type: 'USB',
      rating: '3.5',
      images: require('./pics/8.png'),
      description:
        'PC Keyboard for Office/Home Work - Low-profile Keys Provide Comfortable Typing Experience.Tilt stands with Ergonomic design release your hand from fatigue.White LED Backlit Keyboard - Simple Office style design with single white color backlit, easy typing in dark environment. Ideal for study, Office/Home Work. The backlit can be turned on and off',
    },
    {
      id: '9',
      categoryid: '2',
      name: 'Lenovo Preferred Pro II',
      price: '20.99',
      type: 'USB',
      rating: '3.9',
      images: require('./pics/9.png'),
      description:
        'Lenovo Preferred Pro II Wired External USB Keyboard ( 4X30M86879) Factory Sealed Retail Product For USA / English.Lenovo Standard Wired External Full Size Keybiard. It is configurable 104/105/106/107/109 key layout with languages according to customer',
    },
    {
      id: '10',
      categoryid: '2',
      name: 'A4tech KD-600L Ultra Slim',
      price: '32.58',
      type: 'USB',
      rating: '4.5',
      images: require('./pics/10.png'),
      description:
        'A4TECH KD-600L LED ILLUMINATED ACCS ULTA SLIM KEYBOARD VIA ERGOGUYS. One-touch hotkeys / Ultra Slim keycaps structure Ultra Slim key-cap structure responsive quiet typing keys',
    },
    {
      id: '11',
      categoryid: '3',
      name: 'Dell 27 LED backlit LCD',
      price: '171.69',
      type: 'FHD 1080p',
      rating: '4.5',
      images: require('./pics/11.png'),
      description:
        'LED-backlit LCD monitor - 27", Aspect Ratio -16:9, Contrast Ratio - 1000:1Panel Type - IPS, Full HD (1080p) 1920 x 1080 at 60 Hz, Response Time - 8 ms (grey-to-grey normal); 5 ms (grey-to-grey fast)Input Connectors - HDMI, VGA Does NOT have VESA Mount',
    },
    {
      id: '12',
      categoryid: '3',
      name: 'HP 24mh FHD',
      price: '157.99',
      type: 'FHD 1080p',
      rating: '3.7',
      images: require('./pics/12.png'),
      description:
        'The HP 24mh FHD Monitor has all the style and performance you need in a monitor without breaking the bank. Experience more desk space than you thought possible with this height-adjustable ultra-slim HP monitor. The attractive, micro-edge design adds stylish beauty to any environment',
    },
    {
      id: '13',
      categoryid: '3',
      name: 'Acer SB220Q bi ',
      price: '93.71',
      type: 'FHD 1080p',
      rating: '3.5',
      images: require('./pics/13.png'),
      description:
        'The Acer SB220Q bi 21. 5" Widescreen LCD IPS display combines stylish ultra-thin functionality with amazing 1920 x 1080 resolution, allowing you to enjoy High-Definition entertainment in the comfort of your home. Incredible 100, 000, 000: 1 contrast ratio and rapid 4ms response time highlight the advanced technology, The SB220Q bi LCD also features multiple inputs (HDMI & VGA) for greater compatibility and a Kensington lock slot to protect your investment.',
    },
    {
      id: '14',
      categoryid: '3',
      name: 'Sceptre 20" 1600x900 75Hz Ultra',
      price: '79.99',
      type: 'HD+',
      rating: '3.6',
      images: require('./pics/14.png'),
      description:
        'At 20", The Sceptre E205W-16003R monitor is your best option for both work and play. 1600 x 900 resolution delivers vivid colors and sharp images on a 20 inch screen. A 5 millisecond response time displays action sequences with the highest Degree of clarity. Enjoy HDMI, DVI, and VGA inputs to connect all video and gaming devices. Signal compatibility: digital signal Frequency - 30 – 80 kHz (horizontal)/ 60 – 75 kHz (vertical), HDMI input signal support',
    },
    {
      id: '15',
      categoryid: '3',
      name: 'Lenovo Q24h-10',
      price: '229.56',
      type: 'QHD Wide 1440p',
      rating: '4.7',
      images: require('./pics/15.png'),
      description:
        'Designed to dazzle in your home office and for your entertainment needs, the Lenovo Q24h-10 23.8-inch monitor is powered to perform. This QHD monitor blends style and performance to offer an unmatched user experience, whether you work from home, are a college student,',
    },
    {
      id: '16',
      categoryid: '4',
      name: 'Sony MDRZX110/BLK ZX ',
      price: '15.85',
      type: 'Wired',
      rating: '3.4',
      images: require('./pics/16.png'),
      description:
        "Maximizing your personal audio experience has never been easier than with SONY ZX-Series Monitor headphones. Built with comfort and performance in mind, there's no need to compromise",
    },
    {
      id: '17',
      categoryid: '4',
      name: 'Picozon Rechargeable',
      price: '24.99',
      type: 'Bluetooth',
      rating: '3.8',
      images: require('./pics/17.png'),
      description:
        'Get enough power to accompany your tedious journey.40mm ultra-thin full-range speaker design, around stereo，make us immersive sound for music.Over ear Wireless Bluetooth 5.0 headphone - 15 meters barrier-free transmission',
    },
    {
      id: '18',
      categoryid: '4',
      name: 'Mokata Volume Limited 85dB',
      price: '18.99',
      type: 'Bluetooth',
      rating: '3.5',
      images: require('./pics/18.png'),
      description:
        "It is designed for 3 years old and up children.Made with high quality, durable materials, these headphone are built to last and withstand the rough play of kids.SAFE&VOLUME CONTROLLED:This kid-sized volume limiting children headphones is set to 85db.max(Default), well prevent your child's hearing being hurt and reducing the risk of permanent hearing damage",
    },
    {
      id: '19',
      categoryid: '4',
      name: 'Hybrid Active Noise',
      price: '63.45',
      type: 'Wireless',
      rating: '4.2',
      images: require('./pics/19.png'),
      description:
        'Hybrid Active Noise Cancelling Technology: SuperEQ Bluetooth headphones come with professional feed-forward and feedback active noise cancelling function to reduce ambient noise up to 33dB. Whether you are in a noisy street, a busy subway station, a bus, or in a flight cabin, just turn on the ANC switch,',
    },
    {
      id: '20',
      categoryid: '4',
      name: 'Yusonic Kids',
      price: '25.69',
      type: 'Wired',
      rating: '4.1',
      images: require('./pics/20.png'),
      description:
        "Works with all portable devices that feature a 3.5mm stereo jack.Kid-Safe volume limiting technology suitable for children ages 3-8.Comfortable wear and no harm to kids' ears Adjustable headband and volume limitation..Stimulate musical potential and intelligence.Soft comfy ear pads",
    },
    {
      id: '21',
      categoryid: '5',
      name: 'EC108MP Gaming Mouse Pad ',
      price: '6.99',
      type: 'Fabric',
      rating: '3.5',
      images: require('./pics/21.png'),
      description:
        'This wrist rest mouse pad helps reduce wrist pain and relieve work pressure. It is an elbow protector for office workers, especially those working in editing.The non-slip rubber base can grisp desk firmly and prevent slippage, thus providing you with stable operation, allowing you to move the mouse freely without interference.',
    },
    {
      id: '22',
      categoryid: '5',
      name: 'Duboonmat Mouse Pad',
      price: '8.99',
      type: 'Cotton',
      rating: '4.1',
      images: require('./pics/22.png'),
      description:
        'Product Dimensions is about 25.5*23*0.3CM(10*9*0.12inches).Ergonomic memory cotton mouse pad with a soft gel palm rest to relieve the pressure on the wrist.Package include 1*wrist rests. Soft silicone to relax your wrist.Environmental protection natural rubber material is certified and has no health hazard.Mouse pad wear resistance is not easy to wrinkle, long life, easy to clean, quick-drying.100% Guarantee If you have any issue with your product, contact us and our team will respond to you within 24 hours.',
    },
    {
      id: '23',
      categoryid: '5',
      name: 'RICHEN Ergonomic PU ',
      price: '7.85',
      type: 'Cotton',
      rating: '3.8',
      images: require('./pics/23.png'),
      description:
        'Our RICHEN Mouse Pad with Wrist Rest the Size About 10.62"*9.64", it is made of high quality faux leather surface and nicely done stitching makes this mouse pad elegant and durable. Waterproof and lightweight. No worries if you spill the water or coffee on the mouse pad, just wipe it clean with a cloth or paper towels. Environment friendly material ensures your healthy.',
    },
    {
      id: '24',
      categoryid: '5',
      name: 'SenseAGE Standard Mouse Pad',
      price: '11.99',
      type: 'Fabric',
      rating: '4.5',
      images: require('./pics/24.png'),
      description:
        'Made with Eco-friendly, soft, smooth and flexible Materials, perfectly comfortable fabric surface.[Upgraded Size]: 8.86 x 6.1 inch mouse pad, excellent tracking surface for mouse and 100% Anti-slide material underneath, fits any type of mice.[Ergonomic Design]: Ergonomically designed with soft and quality sponge cushion. Provide maximum support to your wrists and relieve the pressure and the pain.[Non-slip Rubber Base]: Dense slip-resistant shading can effectively prevent the mouse from sliding and moving.[High Quality Material]: Made by unique Air Mesh',
    },
  ],
};
